services:                   # default tag:v1.0.0
  space-aofs:
    tag: v1.0.0
  space-filepreview:
    tag: v1.0.0
  space-gateway:
    tag: v1.0.0
  space-media-vod:
    tag: v1.0.0
  space-postgresql:
    tag: v1.0.0
  space-web:
    tag: v1.0.0
  space-agent:
    tag: v1.0.0
  space-upgrade:
    tag: v1.0.0

whetherproxy: no   # 是否通过代理来构建docker镜像？/Whether build docker images through a proxy?
httpproxy_address: 127.0.0.1:9989
httpsproxy_address: 127.0.0.1:9989 # 如果代理，在此输入代理地址。 / If using a proxy, enter the proxy address here.
