name: ao-space server build script ci

on:
  push:
    branches:
      - "*"
    paths:
      - "server/**"
      - ".github/workflows/server_ci.yml"
    pull_request:
      branches:
       - "*"
      paths:
       - "server/**"
       - ".github/workflows/server_ci.yml"

jobs:
  server_components_build_and_run:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Install Git
      run: sudo apt-get install -y git

    - name: Install Go
      run: |
        wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go1.20.3.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> $HOME/.profile
        source $HOME/.profile
    
    - name: Initial submodules
      run: |
        cd server
        git submodule init
        git submodule update --remote

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make build
      run: |
        cd server
        make build

    - name: Make run
      run: |
        cd server
        make run